version: 2
    
jobs:
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "gcevangelina@gmail.com"
            git config user.name "evangelinalk"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/_build/html
workflows:
  version: 2
  build:
    jobs:
      - docs-deploy:
          filters:
            branches:
                only: master